// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moodle.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Moodle.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Moodle.Domain.Entities.Announcements.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("content");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Title", "CourseId")
                        .IsUnique();

                    b.ToTable("announcements", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcd886fe-f459-46f4-8164-2c62914ee40c"),
                            Content = "Dobrodošli na kolegij.",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1134),
                            Title = "Dobrodošli"
                        },
                        new
                        {
                            Id = new Guid("8c8ee3a0-602a-4abc-9b6e-90c687f8aca6"),
                            Content = "Dobrodošli na kolegij.",
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1136),
                            Title = "Dobrodošli"
                        },
                        new
                        {
                            Id = new Guid("58bb056f-257b-4dc5-a3a1-c214c5cc5ee3"),
                            Content = "Detalji o kolokviju bit će objavljeni.",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1138),
                            Title = "Kolokvij najava"
                        },
                        new
                        {
                            Id = new Guid("ff8c66d4-cc1e-4690-a668-24b83213e746"),
                            Content = "Kolokvij će se održati sredinom semestra.",
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1141),
                            Title = "Kolokvij najava"
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user1_id");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user2_id");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.ToTable("conversations", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            User1Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            User2Id = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProfessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("professor_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProfessorId");

                    b.ToTable("courses", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Osnove arhitekture digitalnih sustava.",
                            Name = "Arhitektura digitalnih računala",
                            ProfessorId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "Uvod u digitalnu forenziku i analizu dokaza.",
                            Name = "Računalna forenzika",
                            ProfessorId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Enrollments.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("enrollments", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83ed7f4d-1be9-4244-a8d0-7c28456b2c36"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            EnrolledAt = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1079),
                            StudentId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("0312bbbf-652e-49a7-a319-3e3a98c4b5b3"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            EnrolledAt = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1082),
                            StudentId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("53c6a456-2cf2-4f3a-9c15-5f41f21c03c6"),
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            EnrolledAt = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1083),
                            StudentId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Materials.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Name", "CourseId")
                        .IsUnique();

                    b.ToTable("materials", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1111),
                            Name = "Logički sklopovi i vrata",
                            Url = "https://example.com/logicki-sklopovi-i-vrata"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1113),
                            Name = "Memorijski sustavi",
                            Url = "https://example.com/memorijski-sustavi"
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("messages", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e36f8500-908f-434d-b05a-ae9e8db9cb93"),
                            ConversationId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Text = "Poštovani Sven, kako ste?",
                            Timestamp = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1183),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("a358888b-41cf-4624-a534-16d5b017a52b"),
                            ConversationId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Text = "Odlično.",
                            Timestamp = new DateTime(2026, 1, 3, 3, 54, 6, 971, DateTimeKind.Utc).AddTicks(1185),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@moodle.hr",
                            FirstName = "Marko",
                            LastName = "Markić",
                            Password = "Admin@123!",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "sven@moodle.hr",
                            FirstName = "Sven",
                            LastName = "Gotovac",
                            Password = "Professor@123!",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "toni@moodle.hr",
                            FirstName = "Toni",
                            LastName = "Perković",
                            Password = "Professor@456!",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "luka.lukic@moodle.hr",
                            FirstName = "Luka",
                            LastName = "Lukić",
                            Password = "Student@123!",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Email = "mate.matic@moodle.hr",
                            FirstName = "Mate",
                            LastName = "Matić",
                            Password = "Student@456!",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Email = "josipa.josipovic@moodle.hr",
                            FirstName = "Josipa",
                            LastName = "Josipović",
                            Password = "Student@789!",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Announcements.Announcement", b =>
                {
                    b.HasOne("Moodle.Domain.Entities.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Conversations.Conversation", b =>
                {
                    b.HasOne("Moodle.Domain.Entities.Users.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moodle.Domain.Entities.Users.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Courses.Course", b =>
                {
                    b.HasOne("Moodle.Domain.Entities.Users.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Enrollments.Enrollment", b =>
                {
                    b.HasOne("Moodle.Domain.Entities.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moodle.Domain.Entities.Users.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Materials.Material", b =>
                {
                    b.HasOne("Moodle.Domain.Entities.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Moodle.Domain.Entities.Messages.Message", b =>
                {
                    b.HasOne("Moodle.Domain.Entities.Conversations.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moodle.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
